name: Other (Low Priority)
labels: ["low priority"]
body:
  - type: markdown
    attributes:
      value: |
        This issue will have no limitations but with a low priority.
  - type: textarea
    id: other
    attributes:
      label: Write Something Here
    validations:
      required: true
