name: Other (Low Priority)
description: This issue will have no limitations but with a low priority
labels: ["low priority"]
body:
  - type: textarea
    id: other
    attributes:
      label: Write Something Here
    validations:
      required: true
