name: Publish Mod
description: Runs the `publishMod` gradle task

runs:
  using: composite

  steps:
    - name: Publish mod
      shell: bash
      run: |
        chmod +x gradlew
        ./gradlew build publishMod --stacktrace -Porg.gradle.parallel.threads=4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
