name: Build

on:
  workflow_call:
    inputs:
      java-version:
        description: Java version used to run Gradle
        required: false
        type: string
        default: "21"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ${{ github.workspace }}/build/libs
