name: Publish package to GitHub Packages

on:
  workflow_call:
  
permissions:
  contents: read
  packages: write
  
jobs:
  publish:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
