name: Publish Package to GitHub Packages

on:
  workflow_call:
  
permissions:
  contents: read
  packages: write
  
jobs:
  publish:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
          
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts*', '**/*.gradle*', '**/gradle-wrapper.properties', 'build.gradle.kts', 'build.gradle') }}
      - uses: gradle/wrapper-validation-action@v2
      - run: |
          chmod +x gradlew

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
